name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read repository contents for compatibility check
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        # Workaround @grafana/scenes and @grafana/runtime dependency issues until @grafana/runtime#12.3 is released.
        # The libraries work together at runtime but the use of the canary runtime build doesn't satisfy the @grafana/scenes dependency.
        run: npm ci --legacy-peer-deps
      - name: Build plugin
        run: npm run build
      - name: Compatibility check
        run: npx --yes @grafana/levitate@latest is-compatible --path $(find ./src -type f \( -name "module.ts" -o -name "module.tsx" \)) --target @grafana/data,@grafana/ui,@grafana/runtime
