name: Plugins - CD
run-name: Deploy ${{ inputs.branch }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from. Can be used to deploy PRs to dev
        default: main
      environment:
        description: Environment to publish to
        required: true
        type: choice
        options:
          - 'dev'
          - 'ops'
          - 'prod'
      docs-only:
        description: Only publish docs, do not publish the plugin
        default: false
        type: boolean

permissions: {}

env:
  # Scope for the plugin when publishing it to the catalog.
  # Choose between:
  # - 'universal': on-prem + cloud (default)
  # - 'grafana_cloud': cloud only, hidden for on-prem users
  SCOPES: universal

jobs:
  cd:
    name: CD
    uses: grafana/plugin-ci-workflows/.github/wohtmrkflows/cd.yml@ci-cd-workflows/v2.0.0
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      docs-only: ${{ fromJSON(github.event.inputs.docs-only) }}
      scopes: universal
      grafana-cloud-deployment-type: provisioned
      argo-workflow-slack-channel: '#pathfinder-app-release'
      auto-merge-environments: dev,ops
      publish-to-catalog-as-pending: false
      # temp disable while https://github.com/grafana/plugin-actions/pull/118 is being fixed
      run-playwright: false

      # TODO: add here any other CI custom inputs you may need:
      #   https://enghub.grafana-ops.net/docs/default/component/grafana-plugins-platform/plugins-ci-github-actions/010-plugins-ci-github-actions/#customizing-the-workflows-with-inputs
